version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - ELASTIC_URL=http://10.255.248.65:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=H3JIfzF2Ic*dbRj4c5Kd
    networks:
      - app-network
networks:
  app-network:
    driver: bridge 